### ISSUE TITLE
Double notification bar appearing

### ISSUE THREAD

**Issue by fpaiva36834** [ahmedibra28/NEXTjs-boilerplate#2]
![image](https://github.com/ahmedibra28/NEXTjs-boilerplate/assets/72525693/0befda5e-ed4b-4537-b852-f3ad3a753c5b)

Hello I found this error/problem when seeing how your project works
When I click on any of the login save or anything that uses notification bar it always shows up 2.

**Comment by AmirmohammadZarif** [comment]
Hello,
I believe it's happening because the nature of useEffect hook in development environment (I think after React 18), since the component gets mounted twice. You may modify and change reactStrictMode to `false` in `next.config.js`, which will temporarily get rid of this in the development.

**Comment by ahmedibra28** [comment]
> Hello,
> I believe it's happening because the nature of useEffect hook in development environment (I think after React 18), since the component gets mounted twice. You may modify and change reactStrictMode to `false` in `next.config.js`, which will temporarily get rid of this in the development.

Thank you for raising this issue and bringing it to our attention. Regarding the reactStrictMode in Next.js, it's important to note that it is primarily a development mode feature that helps identify potential issues during development. It highlights unsafe lifecycles, legacy API usage, and other features.

In Next.js version 13.4 and above, Strict Mode is set to true by default with the app router. However, if you or your team are not ready to enable Strict Mode for the entire application, you have the flexibility to disable it by setting reactStrictMode: false in your next.config.js file.

Please keep in mind that disabling Strict Mode will only affect the development environment and the warnings it provides. The production build and deployment of your Next.js application will not be impacted.

Once again, we appreciate your feedback and thank you for bringing this to our attention. If you have any further questions or concerns, please let us know.
